name: CI
on: pull_request

jobs:
  test:
    name: Tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Unit Tests
        run: npm run test:unit
